### PR TITLE
composer support

### PR DESCRIPTION
**Pull request by FrankGiesecke**
I've added a composer.json to provide this package via packages.org.

### CODE REVIEW

**Comment by FrankGiesecke** [comment]
Any suggestions on this PR?

**Comment by taitems** [comment]
Woah. Epic PR.

This project is more or less in caretaker mode from my point of view. @usmonster is a legend and has been fielding a lot of requests, but I'll give this a bit of a review and test.

Are you able to put up your hand for any bugs that arise from the rearchitecting?

**Comment by usmonster** [comment]
Hi @FrankGiesecke! Sorry this has gone neglected for some time.

@taitems, the only change in this PR is adding a composer.json, so there's not really much to review. ;)

Since this would be a PHP-specific change and is unrelated to the general use case of this plugin, I would rather close this PR without merging and instead suggest you check out the [Composer Asset Plugin](https://github.com/fxpio/composer-asset-plugin). If your use case is that you want to install the plugin with composer, they have [instructions to do just that](https://github.com/fxpio/composer-asset-plugin/blob/master/Resources/doc/index.md#usage-with-vcs-repository). (We might make it slightly easier by adding a package.json and registering this as an NPM package, but... that would be another ticket. ;) )

That said, I'll close this PR. Thanks for using the plugin and for contributing!

**Comment by taitems** [comment]
@usmonster Usman my man! Good to chat again.

I looked at the 'files changed' tab and there appeared to be a lot more than the composer change?

**Comment by usmonster** [comment]
Hey @taitems! Yeah, I saw that, but it's actually GitHub's interface kind of lying to us. 😬

You'll see in the "Commits" tab that all those other changes actually come from my old commits, which were already merged almost a year before the one relevant commit. Possibly a weird rebase or merge happened at the time of this PR, which could be why the diff still shows these changes... (their hashes are different, but the content is the same). [See the diff](https://github.com/taitems/jQuery.Gantt/compare/master...final-gene:feature/composer-support) for a better view.

**Pull request closed without merging**
